// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

/**
 * Protobuf type {@code ru.itmo.java.message.torrent.FileParts}
 */
public final class FileParts extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itmo.java.message.torrent.FileParts)
    FilePartsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileParts.newBuilder() to construct.
  private FileParts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileParts() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FileParts();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FileParts(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ru.itmo.java.message.torrent.UserInfo.Builder subBuilder = null;
            if (userInfo_ != null) {
              subBuilder = userInfo_.toBuilder();
            }
            userInfo_ = input.readMessage(ru.itmo.java.message.torrent.UserInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userInfo_);
              userInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            idFile_ = input.readInt64();
            break;
          }
          case 24: {

            partOfFile_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_FileParts_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_FileParts_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itmo.java.message.torrent.FileParts.class, ru.itmo.java.message.torrent.FileParts.Builder.class);
  }

  public static final int USERINFO_FIELD_NUMBER = 1;
  private ru.itmo.java.message.torrent.UserInfo userInfo_;
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
   * @return Whether the userInfo field is set.
   */
  @java.lang.Override
  public boolean hasUserInfo() {
    return userInfo_ != null;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
   * @return The userInfo.
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.UserInfo getUserInfo() {
    return userInfo_ == null ? ru.itmo.java.message.torrent.UserInfo.getDefaultInstance() : userInfo_;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.UserInfoOrBuilder getUserInfoOrBuilder() {
    return getUserInfo();
  }

  public static final int IDFILE_FIELD_NUMBER = 2;
  private long idFile_;
  /**
   * <code>int64 idFile = 2;</code>
   * @return The idFile.
   */
  @java.lang.Override
  public long getIdFile() {
    return idFile_;
  }

  public static final int PARTOFFILE_FIELD_NUMBER = 3;
  private long partOfFile_;
  /**
   * <code>int64 partOfFile = 3;</code>
   * @return The partOfFile.
   */
  @java.lang.Override
  public long getPartOfFile() {
    return partOfFile_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userInfo_ != null) {
      output.writeMessage(1, getUserInfo());
    }
    if (idFile_ != 0L) {
      output.writeInt64(2, idFile_);
    }
    if (partOfFile_ != 0L) {
      output.writeInt64(3, partOfFile_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUserInfo());
    }
    if (idFile_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, idFile_);
    }
    if (partOfFile_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, partOfFile_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itmo.java.message.torrent.FileParts)) {
      return super.equals(obj);
    }
    ru.itmo.java.message.torrent.FileParts other = (ru.itmo.java.message.torrent.FileParts) obj;

    if (hasUserInfo() != other.hasUserInfo()) return false;
    if (hasUserInfo()) {
      if (!getUserInfo()
          .equals(other.getUserInfo())) return false;
    }
    if (getIdFile()
        != other.getIdFile()) return false;
    if (getPartOfFile()
        != other.getPartOfFile()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUserInfo()) {
      hash = (37 * hash) + USERINFO_FIELD_NUMBER;
      hash = (53 * hash) + getUserInfo().hashCode();
    }
    hash = (37 * hash) + IDFILE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdFile());
    hash = (37 * hash) + PARTOFFILE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPartOfFile());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itmo.java.message.torrent.FileParts parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.FileParts parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.FileParts parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.FileParts parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.FileParts parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.FileParts parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.FileParts parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.FileParts parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.FileParts parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.FileParts parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.FileParts parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.FileParts parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itmo.java.message.torrent.FileParts prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itmo.java.message.torrent.FileParts}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itmo.java.message.torrent.FileParts)
      ru.itmo.java.message.torrent.FilePartsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_FileParts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_FileParts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itmo.java.message.torrent.FileParts.class, ru.itmo.java.message.torrent.FileParts.Builder.class);
    }

    // Construct using ru.itmo.java.message.torrent.FileParts.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userInfoBuilder_ == null) {
        userInfo_ = null;
      } else {
        userInfo_ = null;
        userInfoBuilder_ = null;
      }
      idFile_ = 0L;

      partOfFile_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_FileParts_descriptor;
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.FileParts getDefaultInstanceForType() {
      return ru.itmo.java.message.torrent.FileParts.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.FileParts build() {
      ru.itmo.java.message.torrent.FileParts result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.FileParts buildPartial() {
      ru.itmo.java.message.torrent.FileParts result = new ru.itmo.java.message.torrent.FileParts(this);
      if (userInfoBuilder_ == null) {
        result.userInfo_ = userInfo_;
      } else {
        result.userInfo_ = userInfoBuilder_.build();
      }
      result.idFile_ = idFile_;
      result.partOfFile_ = partOfFile_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itmo.java.message.torrent.FileParts) {
        return mergeFrom((ru.itmo.java.message.torrent.FileParts)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itmo.java.message.torrent.FileParts other) {
      if (other == ru.itmo.java.message.torrent.FileParts.getDefaultInstance()) return this;
      if (other.hasUserInfo()) {
        mergeUserInfo(other.getUserInfo());
      }
      if (other.getIdFile() != 0L) {
        setIdFile(other.getIdFile());
      }
      if (other.getPartOfFile() != 0L) {
        setPartOfFile(other.getPartOfFile());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.itmo.java.message.torrent.FileParts parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.itmo.java.message.torrent.FileParts) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private ru.itmo.java.message.torrent.UserInfo userInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.UserInfo, ru.itmo.java.message.torrent.UserInfo.Builder, ru.itmo.java.message.torrent.UserInfoOrBuilder> userInfoBuilder_;
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
     * @return Whether the userInfo field is set.
     */
    public boolean hasUserInfo() {
      return userInfoBuilder_ != null || userInfo_ != null;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
     * @return The userInfo.
     */
    public ru.itmo.java.message.torrent.UserInfo getUserInfo() {
      if (userInfoBuilder_ == null) {
        return userInfo_ == null ? ru.itmo.java.message.torrent.UserInfo.getDefaultInstance() : userInfo_;
      } else {
        return userInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
     */
    public Builder setUserInfo(ru.itmo.java.message.torrent.UserInfo value) {
      if (userInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userInfo_ = value;
        onChanged();
      } else {
        userInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
     */
    public Builder setUserInfo(
        ru.itmo.java.message.torrent.UserInfo.Builder builderForValue) {
      if (userInfoBuilder_ == null) {
        userInfo_ = builderForValue.build();
        onChanged();
      } else {
        userInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
     */
    public Builder mergeUserInfo(ru.itmo.java.message.torrent.UserInfo value) {
      if (userInfoBuilder_ == null) {
        if (userInfo_ != null) {
          userInfo_ =
            ru.itmo.java.message.torrent.UserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
        } else {
          userInfo_ = value;
        }
        onChanged();
      } else {
        userInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
     */
    public Builder clearUserInfo() {
      if (userInfoBuilder_ == null) {
        userInfo_ = null;
        onChanged();
      } else {
        userInfo_ = null;
        userInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
     */
    public ru.itmo.java.message.torrent.UserInfo.Builder getUserInfoBuilder() {
      
      onChanged();
      return getUserInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
     */
    public ru.itmo.java.message.torrent.UserInfoOrBuilder getUserInfoOrBuilder() {
      if (userInfoBuilder_ != null) {
        return userInfoBuilder_.getMessageOrBuilder();
      } else {
        return userInfo_ == null ?
            ru.itmo.java.message.torrent.UserInfo.getDefaultInstance() : userInfo_;
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.UserInfo, ru.itmo.java.message.torrent.UserInfo.Builder, ru.itmo.java.message.torrent.UserInfoOrBuilder> 
        getUserInfoFieldBuilder() {
      if (userInfoBuilder_ == null) {
        userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.torrent.UserInfo, ru.itmo.java.message.torrent.UserInfo.Builder, ru.itmo.java.message.torrent.UserInfoOrBuilder>(
                getUserInfo(),
                getParentForChildren(),
                isClean());
        userInfo_ = null;
      }
      return userInfoBuilder_;
    }

    private long idFile_ ;
    /**
     * <code>int64 idFile = 2;</code>
     * @return The idFile.
     */
    @java.lang.Override
    public long getIdFile() {
      return idFile_;
    }
    /**
     * <code>int64 idFile = 2;</code>
     * @param value The idFile to set.
     * @return This builder for chaining.
     */
    public Builder setIdFile(long value) {
      
      idFile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 idFile = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdFile() {
      
      idFile_ = 0L;
      onChanged();
      return this;
    }

    private long partOfFile_ ;
    /**
     * <code>int64 partOfFile = 3;</code>
     * @return The partOfFile.
     */
    @java.lang.Override
    public long getPartOfFile() {
      return partOfFile_;
    }
    /**
     * <code>int64 partOfFile = 3;</code>
     * @param value The partOfFile to set.
     * @return This builder for chaining.
     */
    public Builder setPartOfFile(long value) {
      
      partOfFile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 partOfFile = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartOfFile() {
      
      partOfFile_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itmo.java.message.torrent.FileParts)
  }

  // @@protoc_insertion_point(class_scope:ru.itmo.java.message.torrent.FileParts)
  private static final ru.itmo.java.message.torrent.FileParts DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itmo.java.message.torrent.FileParts();
  }

  public static ru.itmo.java.message.torrent.FileParts getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileParts>
      PARSER = new com.google.protobuf.AbstractParser<FileParts>() {
    @java.lang.Override
    public FileParts parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FileParts(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FileParts> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileParts> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itmo.java.message.torrent.FileParts getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

