// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface FilePartsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.FileParts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
   * @return Whether the userInfo field is set.
   */
  boolean hasUserInfo();
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
   * @return The userInfo.
   */
  ru.itmo.java.message.torrent.UserInfo getUserInfo();
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
   */
  ru.itmo.java.message.torrent.UserInfoOrBuilder getUserInfoOrBuilder();

  /**
   * <code>int64 idFile = 2;</code>
   * @return The idFile.
   */
  long getIdFile();

  /**
   * <code>int64 partOfFile = 3;</code>
   * @return The partOfFile.
   */
  long getPartOfFile();
}
