// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface FileContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.FileContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 idFile = 2;</code>
   * @return The idFile.
   */
  long getIdFile();

  /**
   * <code>string filename = 3;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 3;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>int64 sizeFile = 4;</code>
   * @return The sizeFile.
   */
  long getSizeFile();
}
