// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface GetAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.GetAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes content = 1;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>.ru.itmo.java.message.torrent.FileContent fileContent = 2;</code>
   * @return Whether the fileContent field is set.
   */
  boolean hasFileContent();
  /**
   * <code>.ru.itmo.java.message.torrent.FileContent fileContent = 2;</code>
   * @return The fileContent.
   */
  ru.itmo.java.message.torrent.FileContent getFileContent();
  /**
   * <code>.ru.itmo.java.message.torrent.FileContent fileContent = 2;</code>
   */
  ru.itmo.java.message.torrent.FileContentOrBuilder getFileContentOrBuilder();

  /**
   * <code>int64 partOfFile = 3;</code>
   * @return The partOfFile.
   */
  long getPartOfFile();
}
