// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.GetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 idFile = 1;</code>
   * @return The idFile.
   */
  long getIdFile();

  /**
   * <code>int64 partOfFile = 2;</code>
   * @return The partOfFile.
   */
  long getPartOfFile();
}
