// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface ListAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.ListAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 countFile = 1;</code>
   * @return The countFile.
   */
  long getCountFile();

  /**
   * <code>repeated .ru.itmo.java.message.torrent.FileContent fileContent = 2;</code>
   */
  java.util.List<ru.itmo.java.message.torrent.FileContent> 
      getFileContentList();
  /**
   * <code>repeated .ru.itmo.java.message.torrent.FileContent fileContent = 2;</code>
   */
  ru.itmo.java.message.torrent.FileContent getFileContent(int index);
  /**
   * <code>repeated .ru.itmo.java.message.torrent.FileContent fileContent = 2;</code>
   */
  int getFileContentCount();
  /**
   * <code>repeated .ru.itmo.java.message.torrent.FileContent fileContent = 2;</code>
   */
  java.util.List<? extends ru.itmo.java.message.torrent.FileContentOrBuilder> 
      getFileContentOrBuilderList();
  /**
   * <code>repeated .ru.itmo.java.message.torrent.FileContent fileContent = 2;</code>
   */
  ru.itmo.java.message.torrent.FileContentOrBuilder getFileContentOrBuilder(
      int index);
}
