// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface ListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.ListRequest)
    com.google.protobuf.MessageOrBuilder {
}
