// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface RequestToTrackerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.RequestToTracker)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
   * @return Whether the listRequest field is set.
   */
  boolean hasListRequest();
  /**
   * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
   * @return The listRequest.
   */
  ru.itmo.java.message.torrent.ListRequest getListRequest();
  /**
   * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
   */
  ru.itmo.java.message.torrent.ListRequestOrBuilder getListRequestOrBuilder();

  /**
   * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
   * @return Whether the upload field is set.
   */
  boolean hasUpload();
  /**
   * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
   * @return The upload.
   */
  ru.itmo.java.message.torrent.UploadRequest getUpload();
  /**
   * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
   */
  ru.itmo.java.message.torrent.UploadRequestOrBuilder getUploadOrBuilder();

  /**
   * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
   * @return Whether the sources field is set.
   */
  boolean hasSources();
  /**
   * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
   * @return The sources.
   */
  ru.itmo.java.message.torrent.SourcesRequest getSources();
  /**
   * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
   */
  ru.itmo.java.message.torrent.SourcesRequestOrBuilder getSourcesOrBuilder();

  /**
   * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
   * @return Whether the update field is set.
   */
  boolean hasUpdate();
  /**
   * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
   * @return The update.
   */
  ru.itmo.java.message.torrent.UpdateRequest getUpdate();
  /**
   * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
   */
  ru.itmo.java.message.torrent.UpdateRequestOrBuilder getUpdateOrBuilder();

  public ru.itmo.java.message.torrent.RequestToTracker.RequestCase getRequestCase();
}
