// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

/**
 * Protobuf type {@code ru.itmo.java.message.torrent.RequestToTracker}
 */
public final class RequestToTracker extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itmo.java.message.torrent.RequestToTracker)
    RequestToTrackerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestToTracker.newBuilder() to construct.
  private RequestToTracker(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestToTracker() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestToTracker();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestToTracker(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ru.itmo.java.message.torrent.ListRequest.Builder subBuilder = null;
            if (requestCase_ == 1) {
              subBuilder = ((ru.itmo.java.message.torrent.ListRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.torrent.ListRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.torrent.ListRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 1;
            break;
          }
          case 18: {
            ru.itmo.java.message.torrent.UploadRequest.Builder subBuilder = null;
            if (requestCase_ == 2) {
              subBuilder = ((ru.itmo.java.message.torrent.UploadRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.torrent.UploadRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.torrent.UploadRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 2;
            break;
          }
          case 26: {
            ru.itmo.java.message.torrent.SourcesRequest.Builder subBuilder = null;
            if (requestCase_ == 3) {
              subBuilder = ((ru.itmo.java.message.torrent.SourcesRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.torrent.SourcesRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.torrent.SourcesRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 3;
            break;
          }
          case 34: {
            ru.itmo.java.message.torrent.UpdateRequest.Builder subBuilder = null;
            if (requestCase_ == 4) {
              subBuilder = ((ru.itmo.java.message.torrent.UpdateRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.torrent.UpdateRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.torrent.UpdateRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_RequestToTracker_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_RequestToTracker_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itmo.java.message.torrent.RequestToTracker.class, ru.itmo.java.message.torrent.RequestToTracker.Builder.class);
  }

  private int requestCase_ = 0;
  private java.lang.Object request_;
  public enum RequestCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LISTREQUEST(1),
    UPLOAD(2),
    SOURCES(3),
    UPDATE(4),
    REQUEST_NOT_SET(0);
    private final int value;
    private RequestCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static RequestCase forNumber(int value) {
      switch (value) {
        case 1: return LISTREQUEST;
        case 2: return UPLOAD;
        case 3: return SOURCES;
        case 4: return UPDATE;
        case 0: return REQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RequestCase
  getRequestCase() {
    return RequestCase.forNumber(
        requestCase_);
  }

  public static final int LISTREQUEST_FIELD_NUMBER = 1;
  /**
   * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
   * @return Whether the listRequest field is set.
   */
  @java.lang.Override
  public boolean hasListRequest() {
    return requestCase_ == 1;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
   * @return The listRequest.
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.ListRequest getListRequest() {
    if (requestCase_ == 1) {
       return (ru.itmo.java.message.torrent.ListRequest) request_;
    }
    return ru.itmo.java.message.torrent.ListRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.ListRequestOrBuilder getListRequestOrBuilder() {
    if (requestCase_ == 1) {
       return (ru.itmo.java.message.torrent.ListRequest) request_;
    }
    return ru.itmo.java.message.torrent.ListRequest.getDefaultInstance();
  }

  public static final int UPLOAD_FIELD_NUMBER = 2;
  /**
   * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
   * @return Whether the upload field is set.
   */
  @java.lang.Override
  public boolean hasUpload() {
    return requestCase_ == 2;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
   * @return The upload.
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.UploadRequest getUpload() {
    if (requestCase_ == 2) {
       return (ru.itmo.java.message.torrent.UploadRequest) request_;
    }
    return ru.itmo.java.message.torrent.UploadRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.UploadRequestOrBuilder getUploadOrBuilder() {
    if (requestCase_ == 2) {
       return (ru.itmo.java.message.torrent.UploadRequest) request_;
    }
    return ru.itmo.java.message.torrent.UploadRequest.getDefaultInstance();
  }

  public static final int SOURCES_FIELD_NUMBER = 3;
  /**
   * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
   * @return Whether the sources field is set.
   */
  @java.lang.Override
  public boolean hasSources() {
    return requestCase_ == 3;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
   * @return The sources.
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.SourcesRequest getSources() {
    if (requestCase_ == 3) {
       return (ru.itmo.java.message.torrent.SourcesRequest) request_;
    }
    return ru.itmo.java.message.torrent.SourcesRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.SourcesRequestOrBuilder getSourcesOrBuilder() {
    if (requestCase_ == 3) {
       return (ru.itmo.java.message.torrent.SourcesRequest) request_;
    }
    return ru.itmo.java.message.torrent.SourcesRequest.getDefaultInstance();
  }

  public static final int UPDATE_FIELD_NUMBER = 4;
  /**
   * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
   * @return Whether the update field is set.
   */
  @java.lang.Override
  public boolean hasUpdate() {
    return requestCase_ == 4;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
   * @return The update.
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.UpdateRequest getUpdate() {
    if (requestCase_ == 4) {
       return (ru.itmo.java.message.torrent.UpdateRequest) request_;
    }
    return ru.itmo.java.message.torrent.UpdateRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.UpdateRequestOrBuilder getUpdateOrBuilder() {
    if (requestCase_ == 4) {
       return (ru.itmo.java.message.torrent.UpdateRequest) request_;
    }
    return ru.itmo.java.message.torrent.UpdateRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestCase_ == 1) {
      output.writeMessage(1, (ru.itmo.java.message.torrent.ListRequest) request_);
    }
    if (requestCase_ == 2) {
      output.writeMessage(2, (ru.itmo.java.message.torrent.UploadRequest) request_);
    }
    if (requestCase_ == 3) {
      output.writeMessage(3, (ru.itmo.java.message.torrent.SourcesRequest) request_);
    }
    if (requestCase_ == 4) {
      output.writeMessage(4, (ru.itmo.java.message.torrent.UpdateRequest) request_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (ru.itmo.java.message.torrent.ListRequest) request_);
    }
    if (requestCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ru.itmo.java.message.torrent.UploadRequest) request_);
    }
    if (requestCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (ru.itmo.java.message.torrent.SourcesRequest) request_);
    }
    if (requestCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (ru.itmo.java.message.torrent.UpdateRequest) request_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itmo.java.message.torrent.RequestToTracker)) {
      return super.equals(obj);
    }
    ru.itmo.java.message.torrent.RequestToTracker other = (ru.itmo.java.message.torrent.RequestToTracker) obj;

    if (!getRequestCase().equals(other.getRequestCase())) return false;
    switch (requestCase_) {
      case 1:
        if (!getListRequest()
            .equals(other.getListRequest())) return false;
        break;
      case 2:
        if (!getUpload()
            .equals(other.getUpload())) return false;
        break;
      case 3:
        if (!getSources()
            .equals(other.getSources())) return false;
        break;
      case 4:
        if (!getUpdate()
            .equals(other.getUpdate())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (requestCase_) {
      case 1:
        hash = (37 * hash) + LISTREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getListRequest().hashCode();
        break;
      case 2:
        hash = (37 * hash) + UPLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getUpload().hashCode();
        break;
      case 3:
        hash = (37 * hash) + SOURCES_FIELD_NUMBER;
        hash = (53 * hash) + getSources().hashCode();
        break;
      case 4:
        hash = (37 * hash) + UPDATE_FIELD_NUMBER;
        hash = (53 * hash) + getUpdate().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itmo.java.message.torrent.RequestToTracker parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.RequestToTracker parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.RequestToTracker parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.RequestToTracker parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.RequestToTracker parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.RequestToTracker parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.RequestToTracker parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.RequestToTracker parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.RequestToTracker parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.RequestToTracker parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.RequestToTracker parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.RequestToTracker parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itmo.java.message.torrent.RequestToTracker prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itmo.java.message.torrent.RequestToTracker}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itmo.java.message.torrent.RequestToTracker)
      ru.itmo.java.message.torrent.RequestToTrackerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_RequestToTracker_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_RequestToTracker_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itmo.java.message.torrent.RequestToTracker.class, ru.itmo.java.message.torrent.RequestToTracker.Builder.class);
    }

    // Construct using ru.itmo.java.message.torrent.RequestToTracker.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestCase_ = 0;
      request_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_RequestToTracker_descriptor;
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.RequestToTracker getDefaultInstanceForType() {
      return ru.itmo.java.message.torrent.RequestToTracker.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.RequestToTracker build() {
      ru.itmo.java.message.torrent.RequestToTracker result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.RequestToTracker buildPartial() {
      ru.itmo.java.message.torrent.RequestToTracker result = new ru.itmo.java.message.torrent.RequestToTracker(this);
      if (requestCase_ == 1) {
        if (listRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = listRequestBuilder_.build();
        }
      }
      if (requestCase_ == 2) {
        if (uploadBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = uploadBuilder_.build();
        }
      }
      if (requestCase_ == 3) {
        if (sourcesBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = sourcesBuilder_.build();
        }
      }
      if (requestCase_ == 4) {
        if (updateBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = updateBuilder_.build();
        }
      }
      result.requestCase_ = requestCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itmo.java.message.torrent.RequestToTracker) {
        return mergeFrom((ru.itmo.java.message.torrent.RequestToTracker)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itmo.java.message.torrent.RequestToTracker other) {
      if (other == ru.itmo.java.message.torrent.RequestToTracker.getDefaultInstance()) return this;
      switch (other.getRequestCase()) {
        case LISTREQUEST: {
          mergeListRequest(other.getListRequest());
          break;
        }
        case UPLOAD: {
          mergeUpload(other.getUpload());
          break;
        }
        case SOURCES: {
          mergeSources(other.getSources());
          break;
        }
        case UPDATE: {
          mergeUpdate(other.getUpdate());
          break;
        }
        case REQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.itmo.java.message.torrent.RequestToTracker parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.itmo.java.message.torrent.RequestToTracker) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int requestCase_ = 0;
    private java.lang.Object request_;
    public RequestCase
        getRequestCase() {
      return RequestCase.forNumber(
          requestCase_);
    }

    public Builder clearRequest() {
      requestCase_ = 0;
      request_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.ListRequest, ru.itmo.java.message.torrent.ListRequest.Builder, ru.itmo.java.message.torrent.ListRequestOrBuilder> listRequestBuilder_;
    /**
     * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
     * @return Whether the listRequest field is set.
     */
    @java.lang.Override
    public boolean hasListRequest() {
      return requestCase_ == 1;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
     * @return The listRequest.
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.ListRequest getListRequest() {
      if (listRequestBuilder_ == null) {
        if (requestCase_ == 1) {
          return (ru.itmo.java.message.torrent.ListRequest) request_;
        }
        return ru.itmo.java.message.torrent.ListRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 1) {
          return listRequestBuilder_.getMessage();
        }
        return ru.itmo.java.message.torrent.ListRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
     */
    public Builder setListRequest(ru.itmo.java.message.torrent.ListRequest value) {
      if (listRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        listRequestBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
     */
    public Builder setListRequest(
        ru.itmo.java.message.torrent.ListRequest.Builder builderForValue) {
      if (listRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        listRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
     */
    public Builder mergeListRequest(ru.itmo.java.message.torrent.ListRequest value) {
      if (listRequestBuilder_ == null) {
        if (requestCase_ == 1 &&
            request_ != ru.itmo.java.message.torrent.ListRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.torrent.ListRequest.newBuilder((ru.itmo.java.message.torrent.ListRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 1) {
          listRequestBuilder_.mergeFrom(value);
        }
        listRequestBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
     */
    public Builder clearListRequest() {
      if (listRequestBuilder_ == null) {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
        }
        listRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
     */
    public ru.itmo.java.message.torrent.ListRequest.Builder getListRequestBuilder() {
      return getListRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.ListRequestOrBuilder getListRequestOrBuilder() {
      if ((requestCase_ == 1) && (listRequestBuilder_ != null)) {
        return listRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 1) {
          return (ru.itmo.java.message.torrent.ListRequest) request_;
        }
        return ru.itmo.java.message.torrent.ListRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListRequest listRequest = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.ListRequest, ru.itmo.java.message.torrent.ListRequest.Builder, ru.itmo.java.message.torrent.ListRequestOrBuilder> 
        getListRequestFieldBuilder() {
      if (listRequestBuilder_ == null) {
        if (!(requestCase_ == 1)) {
          request_ = ru.itmo.java.message.torrent.ListRequest.getDefaultInstance();
        }
        listRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.torrent.ListRequest, ru.itmo.java.message.torrent.ListRequest.Builder, ru.itmo.java.message.torrent.ListRequestOrBuilder>(
                (ru.itmo.java.message.torrent.ListRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 1;
      onChanged();;
      return listRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.UploadRequest, ru.itmo.java.message.torrent.UploadRequest.Builder, ru.itmo.java.message.torrent.UploadRequestOrBuilder> uploadBuilder_;
    /**
     * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
     * @return Whether the upload field is set.
     */
    @java.lang.Override
    public boolean hasUpload() {
      return requestCase_ == 2;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
     * @return The upload.
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.UploadRequest getUpload() {
      if (uploadBuilder_ == null) {
        if (requestCase_ == 2) {
          return (ru.itmo.java.message.torrent.UploadRequest) request_;
        }
        return ru.itmo.java.message.torrent.UploadRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 2) {
          return uploadBuilder_.getMessage();
        }
        return ru.itmo.java.message.torrent.UploadRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
     */
    public Builder setUpload(ru.itmo.java.message.torrent.UploadRequest value) {
      if (uploadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        uploadBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
     */
    public Builder setUpload(
        ru.itmo.java.message.torrent.UploadRequest.Builder builderForValue) {
      if (uploadBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        uploadBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
     */
    public Builder mergeUpload(ru.itmo.java.message.torrent.UploadRequest value) {
      if (uploadBuilder_ == null) {
        if (requestCase_ == 2 &&
            request_ != ru.itmo.java.message.torrent.UploadRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.torrent.UploadRequest.newBuilder((ru.itmo.java.message.torrent.UploadRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 2) {
          uploadBuilder_.mergeFrom(value);
        }
        uploadBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
     */
    public Builder clearUpload() {
      if (uploadBuilder_ == null) {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
        }
        uploadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
     */
    public ru.itmo.java.message.torrent.UploadRequest.Builder getUploadBuilder() {
      return getUploadFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.UploadRequestOrBuilder getUploadOrBuilder() {
      if ((requestCase_ == 2) && (uploadBuilder_ != null)) {
        return uploadBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 2) {
          return (ru.itmo.java.message.torrent.UploadRequest) request_;
        }
        return ru.itmo.java.message.torrent.UploadRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadRequest upload = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.UploadRequest, ru.itmo.java.message.torrent.UploadRequest.Builder, ru.itmo.java.message.torrent.UploadRequestOrBuilder> 
        getUploadFieldBuilder() {
      if (uploadBuilder_ == null) {
        if (!(requestCase_ == 2)) {
          request_ = ru.itmo.java.message.torrent.UploadRequest.getDefaultInstance();
        }
        uploadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.torrent.UploadRequest, ru.itmo.java.message.torrent.UploadRequest.Builder, ru.itmo.java.message.torrent.UploadRequestOrBuilder>(
                (ru.itmo.java.message.torrent.UploadRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 2;
      onChanged();;
      return uploadBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.SourcesRequest, ru.itmo.java.message.torrent.SourcesRequest.Builder, ru.itmo.java.message.torrent.SourcesRequestOrBuilder> sourcesBuilder_;
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
     * @return Whether the sources field is set.
     */
    @java.lang.Override
    public boolean hasSources() {
      return requestCase_ == 3;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
     * @return The sources.
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.SourcesRequest getSources() {
      if (sourcesBuilder_ == null) {
        if (requestCase_ == 3) {
          return (ru.itmo.java.message.torrent.SourcesRequest) request_;
        }
        return ru.itmo.java.message.torrent.SourcesRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 3) {
          return sourcesBuilder_.getMessage();
        }
        return ru.itmo.java.message.torrent.SourcesRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
     */
    public Builder setSources(ru.itmo.java.message.torrent.SourcesRequest value) {
      if (sourcesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        sourcesBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
     */
    public Builder setSources(
        ru.itmo.java.message.torrent.SourcesRequest.Builder builderForValue) {
      if (sourcesBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        sourcesBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
     */
    public Builder mergeSources(ru.itmo.java.message.torrent.SourcesRequest value) {
      if (sourcesBuilder_ == null) {
        if (requestCase_ == 3 &&
            request_ != ru.itmo.java.message.torrent.SourcesRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.torrent.SourcesRequest.newBuilder((ru.itmo.java.message.torrent.SourcesRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 3) {
          sourcesBuilder_.mergeFrom(value);
        }
        sourcesBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
     */
    public Builder clearSources() {
      if (sourcesBuilder_ == null) {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
        }
        sourcesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
     */
    public ru.itmo.java.message.torrent.SourcesRequest.Builder getSourcesBuilder() {
      return getSourcesFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.SourcesRequestOrBuilder getSourcesOrBuilder() {
      if ((requestCase_ == 3) && (sourcesBuilder_ != null)) {
        return sourcesBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 3) {
          return (ru.itmo.java.message.torrent.SourcesRequest) request_;
        }
        return ru.itmo.java.message.torrent.SourcesRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesRequest sources = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.SourcesRequest, ru.itmo.java.message.torrent.SourcesRequest.Builder, ru.itmo.java.message.torrent.SourcesRequestOrBuilder> 
        getSourcesFieldBuilder() {
      if (sourcesBuilder_ == null) {
        if (!(requestCase_ == 3)) {
          request_ = ru.itmo.java.message.torrent.SourcesRequest.getDefaultInstance();
        }
        sourcesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.torrent.SourcesRequest, ru.itmo.java.message.torrent.SourcesRequest.Builder, ru.itmo.java.message.torrent.SourcesRequestOrBuilder>(
                (ru.itmo.java.message.torrent.SourcesRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 3;
      onChanged();;
      return sourcesBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.UpdateRequest, ru.itmo.java.message.torrent.UpdateRequest.Builder, ru.itmo.java.message.torrent.UpdateRequestOrBuilder> updateBuilder_;
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
     * @return Whether the update field is set.
     */
    @java.lang.Override
    public boolean hasUpdate() {
      return requestCase_ == 4;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
     * @return The update.
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.UpdateRequest getUpdate() {
      if (updateBuilder_ == null) {
        if (requestCase_ == 4) {
          return (ru.itmo.java.message.torrent.UpdateRequest) request_;
        }
        return ru.itmo.java.message.torrent.UpdateRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 4) {
          return updateBuilder_.getMessage();
        }
        return ru.itmo.java.message.torrent.UpdateRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
     */
    public Builder setUpdate(ru.itmo.java.message.torrent.UpdateRequest value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        updateBuilder_.setMessage(value);
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
     */
    public Builder setUpdate(
        ru.itmo.java.message.torrent.UpdateRequest.Builder builderForValue) {
      if (updateBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        updateBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
     */
    public Builder mergeUpdate(ru.itmo.java.message.torrent.UpdateRequest value) {
      if (updateBuilder_ == null) {
        if (requestCase_ == 4 &&
            request_ != ru.itmo.java.message.torrent.UpdateRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.torrent.UpdateRequest.newBuilder((ru.itmo.java.message.torrent.UpdateRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 4) {
          updateBuilder_.mergeFrom(value);
        }
        updateBuilder_.setMessage(value);
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
     */
    public Builder clearUpdate() {
      if (updateBuilder_ == null) {
        if (requestCase_ == 4) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 4) {
          requestCase_ = 0;
          request_ = null;
        }
        updateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
     */
    public ru.itmo.java.message.torrent.UpdateRequest.Builder getUpdateBuilder() {
      return getUpdateFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.UpdateRequestOrBuilder getUpdateOrBuilder() {
      if ((requestCase_ == 4) && (updateBuilder_ != null)) {
        return updateBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 4) {
          return (ru.itmo.java.message.torrent.UpdateRequest) request_;
        }
        return ru.itmo.java.message.torrent.UpdateRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateRequest update = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.UpdateRequest, ru.itmo.java.message.torrent.UpdateRequest.Builder, ru.itmo.java.message.torrent.UpdateRequestOrBuilder> 
        getUpdateFieldBuilder() {
      if (updateBuilder_ == null) {
        if (!(requestCase_ == 4)) {
          request_ = ru.itmo.java.message.torrent.UpdateRequest.getDefaultInstance();
        }
        updateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.torrent.UpdateRequest, ru.itmo.java.message.torrent.UpdateRequest.Builder, ru.itmo.java.message.torrent.UpdateRequestOrBuilder>(
                (ru.itmo.java.message.torrent.UpdateRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 4;
      onChanged();;
      return updateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itmo.java.message.torrent.RequestToTracker)
  }

  // @@protoc_insertion_point(class_scope:ru.itmo.java.message.torrent.RequestToTracker)
  private static final ru.itmo.java.message.torrent.RequestToTracker DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itmo.java.message.torrent.RequestToTracker();
  }

  public static ru.itmo.java.message.torrent.RequestToTracker getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestToTracker>
      PARSER = new com.google.protobuf.AbstractParser<RequestToTracker>() {
    @java.lang.Override
    public RequestToTracker parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestToTracker(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestToTracker> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestToTracker> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itmo.java.message.torrent.RequestToTracker getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

