// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

/**
 * Protobuf type {@code ru.itmo.java.message.torrent.ResponseFromClientServer}
 */
public final class ResponseFromClientServer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itmo.java.message.torrent.ResponseFromClientServer)
    ResponseFromClientServerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResponseFromClientServer.newBuilder() to construct.
  private ResponseFromClientServer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResponseFromClientServer() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResponseFromClientServer();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResponseFromClientServer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ru.itmo.java.message.torrent.StatAnswer.Builder subBuilder = null;
            if (responseCase_ == 1) {
              subBuilder = ((ru.itmo.java.message.torrent.StatAnswer) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.torrent.StatAnswer.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.torrent.StatAnswer) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 1;
            break;
          }
          case 18: {
            ru.itmo.java.message.torrent.GetAnswer.Builder subBuilder = null;
            if (responseCase_ == 2) {
              subBuilder = ((ru.itmo.java.message.torrent.GetAnswer) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.torrent.GetAnswer.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.torrent.GetAnswer) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 2;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_ResponseFromClientServer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_ResponseFromClientServer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itmo.java.message.torrent.ResponseFromClientServer.class, ru.itmo.java.message.torrent.ResponseFromClientServer.Builder.class);
  }

  private int responseCase_ = 0;
  private java.lang.Object response_;
  public enum ResponseCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    STATANSWER(1),
    GETANSWER(2),
    RESPONSE_NOT_SET(0);
    private final int value;
    private ResponseCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCase forNumber(int value) {
      switch (value) {
        case 1: return STATANSWER;
        case 2: return GETANSWER;
        case 0: return RESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResponseCase
  getResponseCase() {
    return ResponseCase.forNumber(
        responseCase_);
  }

  public static final int STATANSWER_FIELD_NUMBER = 1;
  /**
   * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
   * @return Whether the statAnswer field is set.
   */
  @java.lang.Override
  public boolean hasStatAnswer() {
    return responseCase_ == 1;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
   * @return The statAnswer.
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.StatAnswer getStatAnswer() {
    if (responseCase_ == 1) {
       return (ru.itmo.java.message.torrent.StatAnswer) response_;
    }
    return ru.itmo.java.message.torrent.StatAnswer.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.StatAnswerOrBuilder getStatAnswerOrBuilder() {
    if (responseCase_ == 1) {
       return (ru.itmo.java.message.torrent.StatAnswer) response_;
    }
    return ru.itmo.java.message.torrent.StatAnswer.getDefaultInstance();
  }

  public static final int GETANSWER_FIELD_NUMBER = 2;
  /**
   * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
   * @return Whether the getAnswer field is set.
   */
  @java.lang.Override
  public boolean hasGetAnswer() {
    return responseCase_ == 2;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
   * @return The getAnswer.
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.GetAnswer getGetAnswer() {
    if (responseCase_ == 2) {
       return (ru.itmo.java.message.torrent.GetAnswer) response_;
    }
    return ru.itmo.java.message.torrent.GetAnswer.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.GetAnswerOrBuilder getGetAnswerOrBuilder() {
    if (responseCase_ == 2) {
       return (ru.itmo.java.message.torrent.GetAnswer) response_;
    }
    return ru.itmo.java.message.torrent.GetAnswer.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responseCase_ == 1) {
      output.writeMessage(1, (ru.itmo.java.message.torrent.StatAnswer) response_);
    }
    if (responseCase_ == 2) {
      output.writeMessage(2, (ru.itmo.java.message.torrent.GetAnswer) response_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responseCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (ru.itmo.java.message.torrent.StatAnswer) response_);
    }
    if (responseCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ru.itmo.java.message.torrent.GetAnswer) response_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itmo.java.message.torrent.ResponseFromClientServer)) {
      return super.equals(obj);
    }
    ru.itmo.java.message.torrent.ResponseFromClientServer other = (ru.itmo.java.message.torrent.ResponseFromClientServer) obj;

    if (!getResponseCase().equals(other.getResponseCase())) return false;
    switch (responseCase_) {
      case 1:
        if (!getStatAnswer()
            .equals(other.getStatAnswer())) return false;
        break;
      case 2:
        if (!getGetAnswer()
            .equals(other.getGetAnswer())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (responseCase_) {
      case 1:
        hash = (37 * hash) + STATANSWER_FIELD_NUMBER;
        hash = (53 * hash) + getStatAnswer().hashCode();
        break;
      case 2:
        hash = (37 * hash) + GETANSWER_FIELD_NUMBER;
        hash = (53 * hash) + getGetAnswer().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itmo.java.message.torrent.ResponseFromClientServer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.ResponseFromClientServer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.ResponseFromClientServer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.ResponseFromClientServer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.ResponseFromClientServer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.ResponseFromClientServer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.ResponseFromClientServer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.ResponseFromClientServer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.ResponseFromClientServer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.ResponseFromClientServer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.ResponseFromClientServer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.ResponseFromClientServer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itmo.java.message.torrent.ResponseFromClientServer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itmo.java.message.torrent.ResponseFromClientServer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itmo.java.message.torrent.ResponseFromClientServer)
      ru.itmo.java.message.torrent.ResponseFromClientServerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_ResponseFromClientServer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_ResponseFromClientServer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itmo.java.message.torrent.ResponseFromClientServer.class, ru.itmo.java.message.torrent.ResponseFromClientServer.Builder.class);
    }

    // Construct using ru.itmo.java.message.torrent.ResponseFromClientServer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      responseCase_ = 0;
      response_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_ResponseFromClientServer_descriptor;
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.ResponseFromClientServer getDefaultInstanceForType() {
      return ru.itmo.java.message.torrent.ResponseFromClientServer.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.ResponseFromClientServer build() {
      ru.itmo.java.message.torrent.ResponseFromClientServer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.ResponseFromClientServer buildPartial() {
      ru.itmo.java.message.torrent.ResponseFromClientServer result = new ru.itmo.java.message.torrent.ResponseFromClientServer(this);
      if (responseCase_ == 1) {
        if (statAnswerBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = statAnswerBuilder_.build();
        }
      }
      if (responseCase_ == 2) {
        if (getAnswerBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = getAnswerBuilder_.build();
        }
      }
      result.responseCase_ = responseCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itmo.java.message.torrent.ResponseFromClientServer) {
        return mergeFrom((ru.itmo.java.message.torrent.ResponseFromClientServer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itmo.java.message.torrent.ResponseFromClientServer other) {
      if (other == ru.itmo.java.message.torrent.ResponseFromClientServer.getDefaultInstance()) return this;
      switch (other.getResponseCase()) {
        case STATANSWER: {
          mergeStatAnswer(other.getStatAnswer());
          break;
        }
        case GETANSWER: {
          mergeGetAnswer(other.getGetAnswer());
          break;
        }
        case RESPONSE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.itmo.java.message.torrent.ResponseFromClientServer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.itmo.java.message.torrent.ResponseFromClientServer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int responseCase_ = 0;
    private java.lang.Object response_;
    public ResponseCase
        getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    public Builder clearResponse() {
      responseCase_ = 0;
      response_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.StatAnswer, ru.itmo.java.message.torrent.StatAnswer.Builder, ru.itmo.java.message.torrent.StatAnswerOrBuilder> statAnswerBuilder_;
    /**
     * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
     * @return Whether the statAnswer field is set.
     */
    @java.lang.Override
    public boolean hasStatAnswer() {
      return responseCase_ == 1;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
     * @return The statAnswer.
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.StatAnswer getStatAnswer() {
      if (statAnswerBuilder_ == null) {
        if (responseCase_ == 1) {
          return (ru.itmo.java.message.torrent.StatAnswer) response_;
        }
        return ru.itmo.java.message.torrent.StatAnswer.getDefaultInstance();
      } else {
        if (responseCase_ == 1) {
          return statAnswerBuilder_.getMessage();
        }
        return ru.itmo.java.message.torrent.StatAnswer.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
     */
    public Builder setStatAnswer(ru.itmo.java.message.torrent.StatAnswer value) {
      if (statAnswerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        statAnswerBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
     */
    public Builder setStatAnswer(
        ru.itmo.java.message.torrent.StatAnswer.Builder builderForValue) {
      if (statAnswerBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        statAnswerBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
     */
    public Builder mergeStatAnswer(ru.itmo.java.message.torrent.StatAnswer value) {
      if (statAnswerBuilder_ == null) {
        if (responseCase_ == 1 &&
            response_ != ru.itmo.java.message.torrent.StatAnswer.getDefaultInstance()) {
          response_ = ru.itmo.java.message.torrent.StatAnswer.newBuilder((ru.itmo.java.message.torrent.StatAnswer) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 1) {
          statAnswerBuilder_.mergeFrom(value);
        }
        statAnswerBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
     */
    public Builder clearStatAnswer() {
      if (statAnswerBuilder_ == null) {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
        }
        statAnswerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
     */
    public ru.itmo.java.message.torrent.StatAnswer.Builder getStatAnswerBuilder() {
      return getStatAnswerFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.StatAnswerOrBuilder getStatAnswerOrBuilder() {
      if ((responseCase_ == 1) && (statAnswerBuilder_ != null)) {
        return statAnswerBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 1) {
          return (ru.itmo.java.message.torrent.StatAnswer) response_;
        }
        return ru.itmo.java.message.torrent.StatAnswer.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.StatAnswer, ru.itmo.java.message.torrent.StatAnswer.Builder, ru.itmo.java.message.torrent.StatAnswerOrBuilder> 
        getStatAnswerFieldBuilder() {
      if (statAnswerBuilder_ == null) {
        if (!(responseCase_ == 1)) {
          response_ = ru.itmo.java.message.torrent.StatAnswer.getDefaultInstance();
        }
        statAnswerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.torrent.StatAnswer, ru.itmo.java.message.torrent.StatAnswer.Builder, ru.itmo.java.message.torrent.StatAnswerOrBuilder>(
                (ru.itmo.java.message.torrent.StatAnswer) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 1;
      onChanged();;
      return statAnswerBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.GetAnswer, ru.itmo.java.message.torrent.GetAnswer.Builder, ru.itmo.java.message.torrent.GetAnswerOrBuilder> getAnswerBuilder_;
    /**
     * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
     * @return Whether the getAnswer field is set.
     */
    @java.lang.Override
    public boolean hasGetAnswer() {
      return responseCase_ == 2;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
     * @return The getAnswer.
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.GetAnswer getGetAnswer() {
      if (getAnswerBuilder_ == null) {
        if (responseCase_ == 2) {
          return (ru.itmo.java.message.torrent.GetAnswer) response_;
        }
        return ru.itmo.java.message.torrent.GetAnswer.getDefaultInstance();
      } else {
        if (responseCase_ == 2) {
          return getAnswerBuilder_.getMessage();
        }
        return ru.itmo.java.message.torrent.GetAnswer.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
     */
    public Builder setGetAnswer(ru.itmo.java.message.torrent.GetAnswer value) {
      if (getAnswerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        getAnswerBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
     */
    public Builder setGetAnswer(
        ru.itmo.java.message.torrent.GetAnswer.Builder builderForValue) {
      if (getAnswerBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        getAnswerBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
     */
    public Builder mergeGetAnswer(ru.itmo.java.message.torrent.GetAnswer value) {
      if (getAnswerBuilder_ == null) {
        if (responseCase_ == 2 &&
            response_ != ru.itmo.java.message.torrent.GetAnswer.getDefaultInstance()) {
          response_ = ru.itmo.java.message.torrent.GetAnswer.newBuilder((ru.itmo.java.message.torrent.GetAnswer) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 2) {
          getAnswerBuilder_.mergeFrom(value);
        }
        getAnswerBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
     */
    public Builder clearGetAnswer() {
      if (getAnswerBuilder_ == null) {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
        }
        getAnswerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
     */
    public ru.itmo.java.message.torrent.GetAnswer.Builder getGetAnswerBuilder() {
      return getGetAnswerFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.GetAnswerOrBuilder getGetAnswerOrBuilder() {
      if ((responseCase_ == 2) && (getAnswerBuilder_ != null)) {
        return getAnswerBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 2) {
          return (ru.itmo.java.message.torrent.GetAnswer) response_;
        }
        return ru.itmo.java.message.torrent.GetAnswer.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.GetAnswer, ru.itmo.java.message.torrent.GetAnswer.Builder, ru.itmo.java.message.torrent.GetAnswerOrBuilder> 
        getGetAnswerFieldBuilder() {
      if (getAnswerBuilder_ == null) {
        if (!(responseCase_ == 2)) {
          response_ = ru.itmo.java.message.torrent.GetAnswer.getDefaultInstance();
        }
        getAnswerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.torrent.GetAnswer, ru.itmo.java.message.torrent.GetAnswer.Builder, ru.itmo.java.message.torrent.GetAnswerOrBuilder>(
                (ru.itmo.java.message.torrent.GetAnswer) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 2;
      onChanged();;
      return getAnswerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itmo.java.message.torrent.ResponseFromClientServer)
  }

  // @@protoc_insertion_point(class_scope:ru.itmo.java.message.torrent.ResponseFromClientServer)
  private static final ru.itmo.java.message.torrent.ResponseFromClientServer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itmo.java.message.torrent.ResponseFromClientServer();
  }

  public static ru.itmo.java.message.torrent.ResponseFromClientServer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseFromClientServer>
      PARSER = new com.google.protobuf.AbstractParser<ResponseFromClientServer>() {
    @java.lang.Override
    public ResponseFromClientServer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResponseFromClientServer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseFromClientServer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseFromClientServer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itmo.java.message.torrent.ResponseFromClientServer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

