// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

/**
 * Protobuf type {@code ru.itmo.java.message.torrent.ResponseFromTracker}
 */
public final class ResponseFromTracker extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itmo.java.message.torrent.ResponseFromTracker)
    ResponseFromTrackerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResponseFromTracker.newBuilder() to construct.
  private ResponseFromTracker(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResponseFromTracker() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResponseFromTracker();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResponseFromTracker(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ru.itmo.java.message.torrent.ListAnswer.Builder subBuilder = null;
            if (responseCase_ == 1) {
              subBuilder = ((ru.itmo.java.message.torrent.ListAnswer) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.torrent.ListAnswer.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.torrent.ListAnswer) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 1;
            break;
          }
          case 18: {
            ru.itmo.java.message.torrent.UploadAnswer.Builder subBuilder = null;
            if (responseCase_ == 2) {
              subBuilder = ((ru.itmo.java.message.torrent.UploadAnswer) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.torrent.UploadAnswer.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.torrent.UploadAnswer) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 2;
            break;
          }
          case 26: {
            ru.itmo.java.message.torrent.SourcesAnswer.Builder subBuilder = null;
            if (responseCase_ == 3) {
              subBuilder = ((ru.itmo.java.message.torrent.SourcesAnswer) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.torrent.SourcesAnswer.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.torrent.SourcesAnswer) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 3;
            break;
          }
          case 34: {
            ru.itmo.java.message.torrent.UpdateAnswer.Builder subBuilder = null;
            if (responseCase_ == 4) {
              subBuilder = ((ru.itmo.java.message.torrent.UpdateAnswer) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.torrent.UpdateAnswer.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.torrent.UpdateAnswer) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_ResponseFromTracker_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_ResponseFromTracker_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itmo.java.message.torrent.ResponseFromTracker.class, ru.itmo.java.message.torrent.ResponseFromTracker.Builder.class);
  }

  private int responseCase_ = 0;
  private java.lang.Object response_;
  public enum ResponseCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LISTANSWER(1),
    UPLOADANSWER(2),
    SOURCESANSWER(3),
    UPDATEANSWER(4),
    RESPONSE_NOT_SET(0);
    private final int value;
    private ResponseCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCase forNumber(int value) {
      switch (value) {
        case 1: return LISTANSWER;
        case 2: return UPLOADANSWER;
        case 3: return SOURCESANSWER;
        case 4: return UPDATEANSWER;
        case 0: return RESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResponseCase
  getResponseCase() {
    return ResponseCase.forNumber(
        responseCase_);
  }

  public static final int LISTANSWER_FIELD_NUMBER = 1;
  /**
   * <code>.ru.itmo.java.message.torrent.ListAnswer listAnswer = 1;</code>
   * @return Whether the listAnswer field is set.
   */
  @java.lang.Override
  public boolean hasListAnswer() {
    return responseCase_ == 1;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.ListAnswer listAnswer = 1;</code>
   * @return The listAnswer.
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.ListAnswer getListAnswer() {
    if (responseCase_ == 1) {
       return (ru.itmo.java.message.torrent.ListAnswer) response_;
    }
    return ru.itmo.java.message.torrent.ListAnswer.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.torrent.ListAnswer listAnswer = 1;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.ListAnswerOrBuilder getListAnswerOrBuilder() {
    if (responseCase_ == 1) {
       return (ru.itmo.java.message.torrent.ListAnswer) response_;
    }
    return ru.itmo.java.message.torrent.ListAnswer.getDefaultInstance();
  }

  public static final int UPLOADANSWER_FIELD_NUMBER = 2;
  /**
   * <code>.ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 2;</code>
   * @return Whether the uploadAnswer field is set.
   */
  @java.lang.Override
  public boolean hasUploadAnswer() {
    return responseCase_ == 2;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 2;</code>
   * @return The uploadAnswer.
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.UploadAnswer getUploadAnswer() {
    if (responseCase_ == 2) {
       return (ru.itmo.java.message.torrent.UploadAnswer) response_;
    }
    return ru.itmo.java.message.torrent.UploadAnswer.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 2;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.UploadAnswerOrBuilder getUploadAnswerOrBuilder() {
    if (responseCase_ == 2) {
       return (ru.itmo.java.message.torrent.UploadAnswer) response_;
    }
    return ru.itmo.java.message.torrent.UploadAnswer.getDefaultInstance();
  }

  public static final int SOURCESANSWER_FIELD_NUMBER = 3;
  /**
   * <code>.ru.itmo.java.message.torrent.SourcesAnswer sourcesAnswer = 3;</code>
   * @return Whether the sourcesAnswer field is set.
   */
  @java.lang.Override
  public boolean hasSourcesAnswer() {
    return responseCase_ == 3;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.SourcesAnswer sourcesAnswer = 3;</code>
   * @return The sourcesAnswer.
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.SourcesAnswer getSourcesAnswer() {
    if (responseCase_ == 3) {
       return (ru.itmo.java.message.torrent.SourcesAnswer) response_;
    }
    return ru.itmo.java.message.torrent.SourcesAnswer.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.torrent.SourcesAnswer sourcesAnswer = 3;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.SourcesAnswerOrBuilder getSourcesAnswerOrBuilder() {
    if (responseCase_ == 3) {
       return (ru.itmo.java.message.torrent.SourcesAnswer) response_;
    }
    return ru.itmo.java.message.torrent.SourcesAnswer.getDefaultInstance();
  }

  public static final int UPDATEANSWER_FIELD_NUMBER = 4;
  /**
   * <code>.ru.itmo.java.message.torrent.UpdateAnswer updateAnswer = 4;</code>
   * @return Whether the updateAnswer field is set.
   */
  @java.lang.Override
  public boolean hasUpdateAnswer() {
    return responseCase_ == 4;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.UpdateAnswer updateAnswer = 4;</code>
   * @return The updateAnswer.
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.UpdateAnswer getUpdateAnswer() {
    if (responseCase_ == 4) {
       return (ru.itmo.java.message.torrent.UpdateAnswer) response_;
    }
    return ru.itmo.java.message.torrent.UpdateAnswer.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.torrent.UpdateAnswer updateAnswer = 4;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.UpdateAnswerOrBuilder getUpdateAnswerOrBuilder() {
    if (responseCase_ == 4) {
       return (ru.itmo.java.message.torrent.UpdateAnswer) response_;
    }
    return ru.itmo.java.message.torrent.UpdateAnswer.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responseCase_ == 1) {
      output.writeMessage(1, (ru.itmo.java.message.torrent.ListAnswer) response_);
    }
    if (responseCase_ == 2) {
      output.writeMessage(2, (ru.itmo.java.message.torrent.UploadAnswer) response_);
    }
    if (responseCase_ == 3) {
      output.writeMessage(3, (ru.itmo.java.message.torrent.SourcesAnswer) response_);
    }
    if (responseCase_ == 4) {
      output.writeMessage(4, (ru.itmo.java.message.torrent.UpdateAnswer) response_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responseCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (ru.itmo.java.message.torrent.ListAnswer) response_);
    }
    if (responseCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ru.itmo.java.message.torrent.UploadAnswer) response_);
    }
    if (responseCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (ru.itmo.java.message.torrent.SourcesAnswer) response_);
    }
    if (responseCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (ru.itmo.java.message.torrent.UpdateAnswer) response_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itmo.java.message.torrent.ResponseFromTracker)) {
      return super.equals(obj);
    }
    ru.itmo.java.message.torrent.ResponseFromTracker other = (ru.itmo.java.message.torrent.ResponseFromTracker) obj;

    if (!getResponseCase().equals(other.getResponseCase())) return false;
    switch (responseCase_) {
      case 1:
        if (!getListAnswer()
            .equals(other.getListAnswer())) return false;
        break;
      case 2:
        if (!getUploadAnswer()
            .equals(other.getUploadAnswer())) return false;
        break;
      case 3:
        if (!getSourcesAnswer()
            .equals(other.getSourcesAnswer())) return false;
        break;
      case 4:
        if (!getUpdateAnswer()
            .equals(other.getUpdateAnswer())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (responseCase_) {
      case 1:
        hash = (37 * hash) + LISTANSWER_FIELD_NUMBER;
        hash = (53 * hash) + getListAnswer().hashCode();
        break;
      case 2:
        hash = (37 * hash) + UPLOADANSWER_FIELD_NUMBER;
        hash = (53 * hash) + getUploadAnswer().hashCode();
        break;
      case 3:
        hash = (37 * hash) + SOURCESANSWER_FIELD_NUMBER;
        hash = (53 * hash) + getSourcesAnswer().hashCode();
        break;
      case 4:
        hash = (37 * hash) + UPDATEANSWER_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateAnswer().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itmo.java.message.torrent.ResponseFromTracker parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.ResponseFromTracker parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.ResponseFromTracker parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.ResponseFromTracker parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.ResponseFromTracker parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.ResponseFromTracker parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.ResponseFromTracker parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.ResponseFromTracker parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.ResponseFromTracker parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.ResponseFromTracker parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.ResponseFromTracker parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.ResponseFromTracker parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itmo.java.message.torrent.ResponseFromTracker prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itmo.java.message.torrent.ResponseFromTracker}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itmo.java.message.torrent.ResponseFromTracker)
      ru.itmo.java.message.torrent.ResponseFromTrackerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_ResponseFromTracker_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_ResponseFromTracker_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itmo.java.message.torrent.ResponseFromTracker.class, ru.itmo.java.message.torrent.ResponseFromTracker.Builder.class);
    }

    // Construct using ru.itmo.java.message.torrent.ResponseFromTracker.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      responseCase_ = 0;
      response_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_ResponseFromTracker_descriptor;
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.ResponseFromTracker getDefaultInstanceForType() {
      return ru.itmo.java.message.torrent.ResponseFromTracker.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.ResponseFromTracker build() {
      ru.itmo.java.message.torrent.ResponseFromTracker result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.ResponseFromTracker buildPartial() {
      ru.itmo.java.message.torrent.ResponseFromTracker result = new ru.itmo.java.message.torrent.ResponseFromTracker(this);
      if (responseCase_ == 1) {
        if (listAnswerBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = listAnswerBuilder_.build();
        }
      }
      if (responseCase_ == 2) {
        if (uploadAnswerBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = uploadAnswerBuilder_.build();
        }
      }
      if (responseCase_ == 3) {
        if (sourcesAnswerBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = sourcesAnswerBuilder_.build();
        }
      }
      if (responseCase_ == 4) {
        if (updateAnswerBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = updateAnswerBuilder_.build();
        }
      }
      result.responseCase_ = responseCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itmo.java.message.torrent.ResponseFromTracker) {
        return mergeFrom((ru.itmo.java.message.torrent.ResponseFromTracker)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itmo.java.message.torrent.ResponseFromTracker other) {
      if (other == ru.itmo.java.message.torrent.ResponseFromTracker.getDefaultInstance()) return this;
      switch (other.getResponseCase()) {
        case LISTANSWER: {
          mergeListAnswer(other.getListAnswer());
          break;
        }
        case UPLOADANSWER: {
          mergeUploadAnswer(other.getUploadAnswer());
          break;
        }
        case SOURCESANSWER: {
          mergeSourcesAnswer(other.getSourcesAnswer());
          break;
        }
        case UPDATEANSWER: {
          mergeUpdateAnswer(other.getUpdateAnswer());
          break;
        }
        case RESPONSE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.itmo.java.message.torrent.ResponseFromTracker parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.itmo.java.message.torrent.ResponseFromTracker) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int responseCase_ = 0;
    private java.lang.Object response_;
    public ResponseCase
        getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    public Builder clearResponse() {
      responseCase_ = 0;
      response_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.ListAnswer, ru.itmo.java.message.torrent.ListAnswer.Builder, ru.itmo.java.message.torrent.ListAnswerOrBuilder> listAnswerBuilder_;
    /**
     * <code>.ru.itmo.java.message.torrent.ListAnswer listAnswer = 1;</code>
     * @return Whether the listAnswer field is set.
     */
    @java.lang.Override
    public boolean hasListAnswer() {
      return responseCase_ == 1;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListAnswer listAnswer = 1;</code>
     * @return The listAnswer.
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.ListAnswer getListAnswer() {
      if (listAnswerBuilder_ == null) {
        if (responseCase_ == 1) {
          return (ru.itmo.java.message.torrent.ListAnswer) response_;
        }
        return ru.itmo.java.message.torrent.ListAnswer.getDefaultInstance();
      } else {
        if (responseCase_ == 1) {
          return listAnswerBuilder_.getMessage();
        }
        return ru.itmo.java.message.torrent.ListAnswer.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListAnswer listAnswer = 1;</code>
     */
    public Builder setListAnswer(ru.itmo.java.message.torrent.ListAnswer value) {
      if (listAnswerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        listAnswerBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListAnswer listAnswer = 1;</code>
     */
    public Builder setListAnswer(
        ru.itmo.java.message.torrent.ListAnswer.Builder builderForValue) {
      if (listAnswerBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        listAnswerBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListAnswer listAnswer = 1;</code>
     */
    public Builder mergeListAnswer(ru.itmo.java.message.torrent.ListAnswer value) {
      if (listAnswerBuilder_ == null) {
        if (responseCase_ == 1 &&
            response_ != ru.itmo.java.message.torrent.ListAnswer.getDefaultInstance()) {
          response_ = ru.itmo.java.message.torrent.ListAnswer.newBuilder((ru.itmo.java.message.torrent.ListAnswer) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 1) {
          listAnswerBuilder_.mergeFrom(value);
        }
        listAnswerBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListAnswer listAnswer = 1;</code>
     */
    public Builder clearListAnswer() {
      if (listAnswerBuilder_ == null) {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
        }
        listAnswerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListAnswer listAnswer = 1;</code>
     */
    public ru.itmo.java.message.torrent.ListAnswer.Builder getListAnswerBuilder() {
      return getListAnswerFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListAnswer listAnswer = 1;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.ListAnswerOrBuilder getListAnswerOrBuilder() {
      if ((responseCase_ == 1) && (listAnswerBuilder_ != null)) {
        return listAnswerBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 1) {
          return (ru.itmo.java.message.torrent.ListAnswer) response_;
        }
        return ru.itmo.java.message.torrent.ListAnswer.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.ListAnswer listAnswer = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.ListAnswer, ru.itmo.java.message.torrent.ListAnswer.Builder, ru.itmo.java.message.torrent.ListAnswerOrBuilder> 
        getListAnswerFieldBuilder() {
      if (listAnswerBuilder_ == null) {
        if (!(responseCase_ == 1)) {
          response_ = ru.itmo.java.message.torrent.ListAnswer.getDefaultInstance();
        }
        listAnswerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.torrent.ListAnswer, ru.itmo.java.message.torrent.ListAnswer.Builder, ru.itmo.java.message.torrent.ListAnswerOrBuilder>(
                (ru.itmo.java.message.torrent.ListAnswer) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 1;
      onChanged();;
      return listAnswerBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.UploadAnswer, ru.itmo.java.message.torrent.UploadAnswer.Builder, ru.itmo.java.message.torrent.UploadAnswerOrBuilder> uploadAnswerBuilder_;
    /**
     * <code>.ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 2;</code>
     * @return Whether the uploadAnswer field is set.
     */
    @java.lang.Override
    public boolean hasUploadAnswer() {
      return responseCase_ == 2;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 2;</code>
     * @return The uploadAnswer.
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.UploadAnswer getUploadAnswer() {
      if (uploadAnswerBuilder_ == null) {
        if (responseCase_ == 2) {
          return (ru.itmo.java.message.torrent.UploadAnswer) response_;
        }
        return ru.itmo.java.message.torrent.UploadAnswer.getDefaultInstance();
      } else {
        if (responseCase_ == 2) {
          return uploadAnswerBuilder_.getMessage();
        }
        return ru.itmo.java.message.torrent.UploadAnswer.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 2;</code>
     */
    public Builder setUploadAnswer(ru.itmo.java.message.torrent.UploadAnswer value) {
      if (uploadAnswerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        uploadAnswerBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 2;</code>
     */
    public Builder setUploadAnswer(
        ru.itmo.java.message.torrent.UploadAnswer.Builder builderForValue) {
      if (uploadAnswerBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        uploadAnswerBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 2;</code>
     */
    public Builder mergeUploadAnswer(ru.itmo.java.message.torrent.UploadAnswer value) {
      if (uploadAnswerBuilder_ == null) {
        if (responseCase_ == 2 &&
            response_ != ru.itmo.java.message.torrent.UploadAnswer.getDefaultInstance()) {
          response_ = ru.itmo.java.message.torrent.UploadAnswer.newBuilder((ru.itmo.java.message.torrent.UploadAnswer) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 2) {
          uploadAnswerBuilder_.mergeFrom(value);
        }
        uploadAnswerBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 2;</code>
     */
    public Builder clearUploadAnswer() {
      if (uploadAnswerBuilder_ == null) {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
        }
        uploadAnswerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 2;</code>
     */
    public ru.itmo.java.message.torrent.UploadAnswer.Builder getUploadAnswerBuilder() {
      return getUploadAnswerFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 2;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.UploadAnswerOrBuilder getUploadAnswerOrBuilder() {
      if ((responseCase_ == 2) && (uploadAnswerBuilder_ != null)) {
        return uploadAnswerBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 2) {
          return (ru.itmo.java.message.torrent.UploadAnswer) response_;
        }
        return ru.itmo.java.message.torrent.UploadAnswer.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.UploadAnswer, ru.itmo.java.message.torrent.UploadAnswer.Builder, ru.itmo.java.message.torrent.UploadAnswerOrBuilder> 
        getUploadAnswerFieldBuilder() {
      if (uploadAnswerBuilder_ == null) {
        if (!(responseCase_ == 2)) {
          response_ = ru.itmo.java.message.torrent.UploadAnswer.getDefaultInstance();
        }
        uploadAnswerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.torrent.UploadAnswer, ru.itmo.java.message.torrent.UploadAnswer.Builder, ru.itmo.java.message.torrent.UploadAnswerOrBuilder>(
                (ru.itmo.java.message.torrent.UploadAnswer) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 2;
      onChanged();;
      return uploadAnswerBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.SourcesAnswer, ru.itmo.java.message.torrent.SourcesAnswer.Builder, ru.itmo.java.message.torrent.SourcesAnswerOrBuilder> sourcesAnswerBuilder_;
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesAnswer sourcesAnswer = 3;</code>
     * @return Whether the sourcesAnswer field is set.
     */
    @java.lang.Override
    public boolean hasSourcesAnswer() {
      return responseCase_ == 3;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesAnswer sourcesAnswer = 3;</code>
     * @return The sourcesAnswer.
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.SourcesAnswer getSourcesAnswer() {
      if (sourcesAnswerBuilder_ == null) {
        if (responseCase_ == 3) {
          return (ru.itmo.java.message.torrent.SourcesAnswer) response_;
        }
        return ru.itmo.java.message.torrent.SourcesAnswer.getDefaultInstance();
      } else {
        if (responseCase_ == 3) {
          return sourcesAnswerBuilder_.getMessage();
        }
        return ru.itmo.java.message.torrent.SourcesAnswer.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesAnswer sourcesAnswer = 3;</code>
     */
    public Builder setSourcesAnswer(ru.itmo.java.message.torrent.SourcesAnswer value) {
      if (sourcesAnswerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        sourcesAnswerBuilder_.setMessage(value);
      }
      responseCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesAnswer sourcesAnswer = 3;</code>
     */
    public Builder setSourcesAnswer(
        ru.itmo.java.message.torrent.SourcesAnswer.Builder builderForValue) {
      if (sourcesAnswerBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        sourcesAnswerBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesAnswer sourcesAnswer = 3;</code>
     */
    public Builder mergeSourcesAnswer(ru.itmo.java.message.torrent.SourcesAnswer value) {
      if (sourcesAnswerBuilder_ == null) {
        if (responseCase_ == 3 &&
            response_ != ru.itmo.java.message.torrent.SourcesAnswer.getDefaultInstance()) {
          response_ = ru.itmo.java.message.torrent.SourcesAnswer.newBuilder((ru.itmo.java.message.torrent.SourcesAnswer) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 3) {
          sourcesAnswerBuilder_.mergeFrom(value);
        }
        sourcesAnswerBuilder_.setMessage(value);
      }
      responseCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesAnswer sourcesAnswer = 3;</code>
     */
    public Builder clearSourcesAnswer() {
      if (sourcesAnswerBuilder_ == null) {
        if (responseCase_ == 3) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 3) {
          responseCase_ = 0;
          response_ = null;
        }
        sourcesAnswerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesAnswer sourcesAnswer = 3;</code>
     */
    public ru.itmo.java.message.torrent.SourcesAnswer.Builder getSourcesAnswerBuilder() {
      return getSourcesAnswerFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesAnswer sourcesAnswer = 3;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.SourcesAnswerOrBuilder getSourcesAnswerOrBuilder() {
      if ((responseCase_ == 3) && (sourcesAnswerBuilder_ != null)) {
        return sourcesAnswerBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 3) {
          return (ru.itmo.java.message.torrent.SourcesAnswer) response_;
        }
        return ru.itmo.java.message.torrent.SourcesAnswer.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.SourcesAnswer sourcesAnswer = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.SourcesAnswer, ru.itmo.java.message.torrent.SourcesAnswer.Builder, ru.itmo.java.message.torrent.SourcesAnswerOrBuilder> 
        getSourcesAnswerFieldBuilder() {
      if (sourcesAnswerBuilder_ == null) {
        if (!(responseCase_ == 3)) {
          response_ = ru.itmo.java.message.torrent.SourcesAnswer.getDefaultInstance();
        }
        sourcesAnswerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.torrent.SourcesAnswer, ru.itmo.java.message.torrent.SourcesAnswer.Builder, ru.itmo.java.message.torrent.SourcesAnswerOrBuilder>(
                (ru.itmo.java.message.torrent.SourcesAnswer) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 3;
      onChanged();;
      return sourcesAnswerBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.UpdateAnswer, ru.itmo.java.message.torrent.UpdateAnswer.Builder, ru.itmo.java.message.torrent.UpdateAnswerOrBuilder> updateAnswerBuilder_;
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateAnswer updateAnswer = 4;</code>
     * @return Whether the updateAnswer field is set.
     */
    @java.lang.Override
    public boolean hasUpdateAnswer() {
      return responseCase_ == 4;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateAnswer updateAnswer = 4;</code>
     * @return The updateAnswer.
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.UpdateAnswer getUpdateAnswer() {
      if (updateAnswerBuilder_ == null) {
        if (responseCase_ == 4) {
          return (ru.itmo.java.message.torrent.UpdateAnswer) response_;
        }
        return ru.itmo.java.message.torrent.UpdateAnswer.getDefaultInstance();
      } else {
        if (responseCase_ == 4) {
          return updateAnswerBuilder_.getMessage();
        }
        return ru.itmo.java.message.torrent.UpdateAnswer.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateAnswer updateAnswer = 4;</code>
     */
    public Builder setUpdateAnswer(ru.itmo.java.message.torrent.UpdateAnswer value) {
      if (updateAnswerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        updateAnswerBuilder_.setMessage(value);
      }
      responseCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateAnswer updateAnswer = 4;</code>
     */
    public Builder setUpdateAnswer(
        ru.itmo.java.message.torrent.UpdateAnswer.Builder builderForValue) {
      if (updateAnswerBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        updateAnswerBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateAnswer updateAnswer = 4;</code>
     */
    public Builder mergeUpdateAnswer(ru.itmo.java.message.torrent.UpdateAnswer value) {
      if (updateAnswerBuilder_ == null) {
        if (responseCase_ == 4 &&
            response_ != ru.itmo.java.message.torrent.UpdateAnswer.getDefaultInstance()) {
          response_ = ru.itmo.java.message.torrent.UpdateAnswer.newBuilder((ru.itmo.java.message.torrent.UpdateAnswer) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 4) {
          updateAnswerBuilder_.mergeFrom(value);
        }
        updateAnswerBuilder_.setMessage(value);
      }
      responseCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateAnswer updateAnswer = 4;</code>
     */
    public Builder clearUpdateAnswer() {
      if (updateAnswerBuilder_ == null) {
        if (responseCase_ == 4) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 4) {
          responseCase_ = 0;
          response_ = null;
        }
        updateAnswerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateAnswer updateAnswer = 4;</code>
     */
    public ru.itmo.java.message.torrent.UpdateAnswer.Builder getUpdateAnswerBuilder() {
      return getUpdateAnswerFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateAnswer updateAnswer = 4;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.torrent.UpdateAnswerOrBuilder getUpdateAnswerOrBuilder() {
      if ((responseCase_ == 4) && (updateAnswerBuilder_ != null)) {
        return updateAnswerBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 4) {
          return (ru.itmo.java.message.torrent.UpdateAnswer) response_;
        }
        return ru.itmo.java.message.torrent.UpdateAnswer.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UpdateAnswer updateAnswer = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.UpdateAnswer, ru.itmo.java.message.torrent.UpdateAnswer.Builder, ru.itmo.java.message.torrent.UpdateAnswerOrBuilder> 
        getUpdateAnswerFieldBuilder() {
      if (updateAnswerBuilder_ == null) {
        if (!(responseCase_ == 4)) {
          response_ = ru.itmo.java.message.torrent.UpdateAnswer.getDefaultInstance();
        }
        updateAnswerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.torrent.UpdateAnswer, ru.itmo.java.message.torrent.UpdateAnswer.Builder, ru.itmo.java.message.torrent.UpdateAnswerOrBuilder>(
                (ru.itmo.java.message.torrent.UpdateAnswer) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 4;
      onChanged();;
      return updateAnswerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itmo.java.message.torrent.ResponseFromTracker)
  }

  // @@protoc_insertion_point(class_scope:ru.itmo.java.message.torrent.ResponseFromTracker)
  private static final ru.itmo.java.message.torrent.ResponseFromTracker DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itmo.java.message.torrent.ResponseFromTracker();
  }

  public static ru.itmo.java.message.torrent.ResponseFromTracker getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseFromTracker>
      PARSER = new com.google.protobuf.AbstractParser<ResponseFromTracker>() {
    @java.lang.Override
    public ResponseFromTracker parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResponseFromTracker(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseFromTracker> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseFromTracker> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itmo.java.message.torrent.ResponseFromTracker getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

