// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface ResponseFromClientServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.ResponseFromClientServer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
   * @return Whether the statAnswer field is set.
   */
  boolean hasStatAnswer();
  /**
   * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
   * @return The statAnswer.
   */
  ru.itmo.java.message.torrent.StatAnswer getStatAnswer();
  /**
   * <code>.ru.itmo.java.message.torrent.StatAnswer statAnswer = 1;</code>
   */
  ru.itmo.java.message.torrent.StatAnswerOrBuilder getStatAnswerOrBuilder();

  /**
   * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
   * @return Whether the getAnswer field is set.
   */
  boolean hasGetAnswer();
  /**
   * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
   * @return The getAnswer.
   */
  ru.itmo.java.message.torrent.GetAnswer getGetAnswer();
  /**
   * <code>.ru.itmo.java.message.torrent.GetAnswer getAnswer = 2;</code>
   */
  ru.itmo.java.message.torrent.GetAnswerOrBuilder getGetAnswerOrBuilder();

  public ru.itmo.java.message.torrent.ResponseFromClientServer.ResponseCase getResponseCase();
}
