// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface SourcesAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.SourcesAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ru.itmo.java.message.torrent.UserInfo clientWithFile = 1;</code>
   */
  java.util.List<ru.itmo.java.message.torrent.UserInfo> 
      getClientWithFileList();
  /**
   * <code>repeated .ru.itmo.java.message.torrent.UserInfo clientWithFile = 1;</code>
   */
  ru.itmo.java.message.torrent.UserInfo getClientWithFile(int index);
  /**
   * <code>repeated .ru.itmo.java.message.torrent.UserInfo clientWithFile = 1;</code>
   */
  int getClientWithFileCount();
  /**
   * <code>repeated .ru.itmo.java.message.torrent.UserInfo clientWithFile = 1;</code>
   */
  java.util.List<? extends ru.itmo.java.message.torrent.UserInfoOrBuilder> 
      getClientWithFileOrBuilderList();
  /**
   * <code>repeated .ru.itmo.java.message.torrent.UserInfo clientWithFile = 1;</code>
   */
  ru.itmo.java.message.torrent.UserInfoOrBuilder getClientWithFileOrBuilder(
      int index);

  /**
   * <code>int64 idFile = 2;</code>
   * @return The idFile.
   */
  long getIdFile();
}
