// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface StatAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.StatAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
   * @return The client.
   */
  ru.itmo.java.message.torrent.UserInfo getClient();
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
   */
  ru.itmo.java.message.torrent.UserInfoOrBuilder getClientOrBuilder();

  /**
   * <code>int64 idFile = 2;</code>
   * @return The idFile.
   */
  long getIdFile();

  /**
   * <code>int64 countOfAvailableParts = 3;</code>
   * @return The countOfAvailableParts.
   */
  long getCountOfAvailableParts();

  /**
   * <code>repeated int64 part = 4;</code>
   * @return A list containing the part.
   */
  java.util.List<java.lang.Long> getPartList();
  /**
   * <code>repeated int64 part = 4;</code>
   * @return The count of part.
   */
  int getPartCount();
  /**
   * <code>repeated int64 part = 4;</code>
   * @param index The index of the element to return.
   * @return The part at the given index.
   */
  long getPart(int index);
}
