// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface StatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.StatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 idFile = 1;</code>
   * @return The idFile.
   */
  long getIdFile();
}
