// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

/**
 * Protobuf type {@code ru.itmo.java.message.torrent.StatAnswer}
 */
public final class StatAnswer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itmo.java.message.torrent.StatAnswer)
    StatAnswerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StatAnswer.newBuilder() to construct.
  private StatAnswer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StatAnswer() {
    part_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StatAnswer();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StatAnswer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ru.itmo.java.message.torrent.UserInfo.Builder subBuilder = null;
            if (client_ != null) {
              subBuilder = client_.toBuilder();
            }
            client_ = input.readMessage(ru.itmo.java.message.torrent.UserInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(client_);
              client_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            idFile_ = input.readInt64();
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              part_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            part_.addLong(input.readInt64());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              part_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              part_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        part_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_StatAnswer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_StatAnswer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itmo.java.message.torrent.StatAnswer.class, ru.itmo.java.message.torrent.StatAnswer.Builder.class);
  }

  public static final int CLIENT_FIELD_NUMBER = 1;
  private ru.itmo.java.message.torrent.UserInfo client_;
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
   * @return Whether the client field is set.
   */
  @java.lang.Override
  public boolean hasClient() {
    return client_ != null;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
   * @return The client.
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.UserInfo getClient() {
    return client_ == null ? ru.itmo.java.message.torrent.UserInfo.getDefaultInstance() : client_;
  }
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.torrent.UserInfoOrBuilder getClientOrBuilder() {
    return getClient();
  }

  public static final int IDFILE_FIELD_NUMBER = 2;
  private long idFile_;
  /**
   * <code>int64 idFile = 2;</code>
   * @return The idFile.
   */
  @java.lang.Override
  public long getIdFile() {
    return idFile_;
  }

  public static final int PART_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.LongList part_;
  /**
   * <code>repeated int64 part = 4;</code>
   * @return A list containing the part.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getPartList() {
    return part_;
  }
  /**
   * <code>repeated int64 part = 4;</code>
   * @return The count of part.
   */
  public int getPartCount() {
    return part_.size();
  }
  /**
   * <code>repeated int64 part = 4;</code>
   * @param index The index of the element to return.
   * @return The part at the given index.
   */
  public long getPart(int index) {
    return part_.getLong(index);
  }
  private int partMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (client_ != null) {
      output.writeMessage(1, getClient());
    }
    if (idFile_ != 0L) {
      output.writeInt64(2, idFile_);
    }
    if (getPartList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(partMemoizedSerializedSize);
    }
    for (int i = 0; i < part_.size(); i++) {
      output.writeInt64NoTag(part_.getLong(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (client_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getClient());
    }
    if (idFile_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, idFile_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < part_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(part_.getLong(i));
      }
      size += dataSize;
      if (!getPartList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      partMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itmo.java.message.torrent.StatAnswer)) {
      return super.equals(obj);
    }
    ru.itmo.java.message.torrent.StatAnswer other = (ru.itmo.java.message.torrent.StatAnswer) obj;

    if (hasClient() != other.hasClient()) return false;
    if (hasClient()) {
      if (!getClient()
          .equals(other.getClient())) return false;
    }
    if (getIdFile()
        != other.getIdFile()) return false;
    if (!getPartList()
        .equals(other.getPartList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasClient()) {
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClient().hashCode();
    }
    hash = (37 * hash) + IDFILE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdFile());
    if (getPartCount() > 0) {
      hash = (37 * hash) + PART_FIELD_NUMBER;
      hash = (53 * hash) + getPartList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itmo.java.message.torrent.StatAnswer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.StatAnswer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.StatAnswer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.StatAnswer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.StatAnswer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.torrent.StatAnswer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.StatAnswer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.StatAnswer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.StatAnswer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.StatAnswer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.torrent.StatAnswer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.torrent.StatAnswer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itmo.java.message.torrent.StatAnswer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itmo.java.message.torrent.StatAnswer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itmo.java.message.torrent.StatAnswer)
      ru.itmo.java.message.torrent.StatAnswerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_StatAnswer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_StatAnswer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itmo.java.message.torrent.StatAnswer.class, ru.itmo.java.message.torrent.StatAnswer.Builder.class);
    }

    // Construct using ru.itmo.java.message.torrent.StatAnswer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (clientBuilder_ == null) {
        client_ = null;
      } else {
        client_ = null;
        clientBuilder_ = null;
      }
      idFile_ = 0L;

      part_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itmo.java.message.torrent.Torrent.internal_static_ru_itmo_java_message_torrent_StatAnswer_descriptor;
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.StatAnswer getDefaultInstanceForType() {
      return ru.itmo.java.message.torrent.StatAnswer.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.StatAnswer build() {
      ru.itmo.java.message.torrent.StatAnswer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itmo.java.message.torrent.StatAnswer buildPartial() {
      ru.itmo.java.message.torrent.StatAnswer result = new ru.itmo.java.message.torrent.StatAnswer(this);
      int from_bitField0_ = bitField0_;
      if (clientBuilder_ == null) {
        result.client_ = client_;
      } else {
        result.client_ = clientBuilder_.build();
      }
      result.idFile_ = idFile_;
      if (((bitField0_ & 0x00000001) != 0)) {
        part_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.part_ = part_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itmo.java.message.torrent.StatAnswer) {
        return mergeFrom((ru.itmo.java.message.torrent.StatAnswer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itmo.java.message.torrent.StatAnswer other) {
      if (other == ru.itmo.java.message.torrent.StatAnswer.getDefaultInstance()) return this;
      if (other.hasClient()) {
        mergeClient(other.getClient());
      }
      if (other.getIdFile() != 0L) {
        setIdFile(other.getIdFile());
      }
      if (!other.part_.isEmpty()) {
        if (part_.isEmpty()) {
          part_ = other.part_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensurePartIsMutable();
          part_.addAll(other.part_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.itmo.java.message.torrent.StatAnswer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.itmo.java.message.torrent.StatAnswer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private ru.itmo.java.message.torrent.UserInfo client_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.UserInfo, ru.itmo.java.message.torrent.UserInfo.Builder, ru.itmo.java.message.torrent.UserInfoOrBuilder> clientBuilder_;
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
     * @return Whether the client field is set.
     */
    public boolean hasClient() {
      return clientBuilder_ != null || client_ != null;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
     * @return The client.
     */
    public ru.itmo.java.message.torrent.UserInfo getClient() {
      if (clientBuilder_ == null) {
        return client_ == null ? ru.itmo.java.message.torrent.UserInfo.getDefaultInstance() : client_;
      } else {
        return clientBuilder_.getMessage();
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
     */
    public Builder setClient(ru.itmo.java.message.torrent.UserInfo value) {
      if (clientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        client_ = value;
        onChanged();
      } else {
        clientBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
     */
    public Builder setClient(
        ru.itmo.java.message.torrent.UserInfo.Builder builderForValue) {
      if (clientBuilder_ == null) {
        client_ = builderForValue.build();
        onChanged();
      } else {
        clientBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
     */
    public Builder mergeClient(ru.itmo.java.message.torrent.UserInfo value) {
      if (clientBuilder_ == null) {
        if (client_ != null) {
          client_ =
            ru.itmo.java.message.torrent.UserInfo.newBuilder(client_).mergeFrom(value).buildPartial();
        } else {
          client_ = value;
        }
        onChanged();
      } else {
        clientBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
     */
    public Builder clearClient() {
      if (clientBuilder_ == null) {
        client_ = null;
        onChanged();
      } else {
        client_ = null;
        clientBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
     */
    public ru.itmo.java.message.torrent.UserInfo.Builder getClientBuilder() {
      
      onChanged();
      return getClientFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
     */
    public ru.itmo.java.message.torrent.UserInfoOrBuilder getClientOrBuilder() {
      if (clientBuilder_ != null) {
        return clientBuilder_.getMessageOrBuilder();
      } else {
        return client_ == null ?
            ru.itmo.java.message.torrent.UserInfo.getDefaultInstance() : client_;
      }
    }
    /**
     * <code>.ru.itmo.java.message.torrent.UserInfo client = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.torrent.UserInfo, ru.itmo.java.message.torrent.UserInfo.Builder, ru.itmo.java.message.torrent.UserInfoOrBuilder> 
        getClientFieldBuilder() {
      if (clientBuilder_ == null) {
        clientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.torrent.UserInfo, ru.itmo.java.message.torrent.UserInfo.Builder, ru.itmo.java.message.torrent.UserInfoOrBuilder>(
                getClient(),
                getParentForChildren(),
                isClean());
        client_ = null;
      }
      return clientBuilder_;
    }

    private long idFile_ ;
    /**
     * <code>int64 idFile = 2;</code>
     * @return The idFile.
     */
    @java.lang.Override
    public long getIdFile() {
      return idFile_;
    }
    /**
     * <code>int64 idFile = 2;</code>
     * @param value The idFile to set.
     * @return This builder for chaining.
     */
    public Builder setIdFile(long value) {
      
      idFile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 idFile = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdFile() {
      
      idFile_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList part_ = emptyLongList();
    private void ensurePartIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        part_ = mutableCopy(part_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 part = 4;</code>
     * @return A list containing the part.
     */
    public java.util.List<java.lang.Long>
        getPartList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(part_) : part_;
    }
    /**
     * <code>repeated int64 part = 4;</code>
     * @return The count of part.
     */
    public int getPartCount() {
      return part_.size();
    }
    /**
     * <code>repeated int64 part = 4;</code>
     * @param index The index of the element to return.
     * @return The part at the given index.
     */
    public long getPart(int index) {
      return part_.getLong(index);
    }
    /**
     * <code>repeated int64 part = 4;</code>
     * @param index The index to set the value at.
     * @param value The part to set.
     * @return This builder for chaining.
     */
    public Builder setPart(
        int index, long value) {
      ensurePartIsMutable();
      part_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 part = 4;</code>
     * @param value The part to add.
     * @return This builder for chaining.
     */
    public Builder addPart(long value) {
      ensurePartIsMutable();
      part_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 part = 4;</code>
     * @param values The part to add.
     * @return This builder for chaining.
     */
    public Builder addAllPart(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensurePartIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, part_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 part = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPart() {
      part_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itmo.java.message.torrent.StatAnswer)
  }

  // @@protoc_insertion_point(class_scope:ru.itmo.java.message.torrent.StatAnswer)
  private static final ru.itmo.java.message.torrent.StatAnswer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itmo.java.message.torrent.StatAnswer();
  }

  public static ru.itmo.java.message.torrent.StatAnswer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StatAnswer>
      PARSER = new com.google.protobuf.AbstractParser<StatAnswer>() {
    @java.lang.Override
    public StatAnswer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StatAnswer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StatAnswer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StatAnswer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itmo.java.message.torrent.StatAnswer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

