// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
   * @return Whether the userInfo field is set.
   */
  boolean hasUserInfo();
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
   * @return The userInfo.
   */
  ru.itmo.java.message.torrent.UserInfo getUserInfo();
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 1;</code>
   */
  ru.itmo.java.message.torrent.UserInfoOrBuilder getUserInfoOrBuilder();

  /**
   * <code>int32 portOfClientServer = 2;</code>
   * @return The portOfClientServer.
   */
  int getPortOfClientServer();

  /**
   * <code>int64 countSharedFiles = 3;</code>
   * @return The countSharedFiles.
   */
  long getCountSharedFiles();

  /**
   * <code>repeated .ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 4;</code>
   */
  java.util.List<ru.itmo.java.message.torrent.UploadAnswer> 
      getUploadAnswerList();
  /**
   * <code>repeated .ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 4;</code>
   */
  ru.itmo.java.message.torrent.UploadAnswer getUploadAnswer(int index);
  /**
   * <code>repeated .ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 4;</code>
   */
  int getUploadAnswerCount();
  /**
   * <code>repeated .ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 4;</code>
   */
  java.util.List<? extends ru.itmo.java.message.torrent.UploadAnswerOrBuilder> 
      getUploadAnswerOrBuilderList();
  /**
   * <code>repeated .ru.itmo.java.message.torrent.UploadAnswer uploadAnswer = 4;</code>
   */
  ru.itmo.java.message.torrent.UploadAnswerOrBuilder getUploadAnswerOrBuilder(
      int index);
}
