// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface UpdateAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.UpdateAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool statusUpdate = 1;</code>
   * @return The statusUpdate.
   */
  boolean getStatusUpdate();
}
