// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface UploadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.UploadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filename = 1;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 1;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>int64 size = 2;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 3;</code>
   * @return Whether the userInfo field is set.
   */
  boolean hasUserInfo();
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 3;</code>
   * @return The userInfo.
   */
  ru.itmo.java.message.torrent.UserInfo getUserInfo();
  /**
   * <code>.ru.itmo.java.message.torrent.UserInfo userInfo = 3;</code>
   */
  ru.itmo.java.message.torrent.UserInfoOrBuilder getUserInfoOrBuilder();
}
