// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface UploadAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.UploadAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 idFile = 1;</code>
   * @return The idFile.
   */
  long getIdFile();

  /**
   * <code>string filename = 2;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 2;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>int64 size = 3;</code>
   * @return The size.
   */
  long getSize();
}
