// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torrent.proto

package ru.itmo.java.message.torrent;

public interface UploadAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.torrent.UploadAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.itmo.java.message.torrent.FileContent fileContent = 1;</code>
   * @return Whether the fileContent field is set.
   */
  boolean hasFileContent();
  /**
   * <code>.ru.itmo.java.message.torrent.FileContent fileContent = 1;</code>
   * @return The fileContent.
   */
  ru.itmo.java.message.torrent.FileContent getFileContent();
  /**
   * <code>.ru.itmo.java.message.torrent.FileContent fileContent = 1;</code>
   */
  ru.itmo.java.message.torrent.FileContentOrBuilder getFileContentOrBuilder();
}
